#!/usr/bin/env python3
"""Run scripts generated by `emit-smoke` and check each step runs once, alone.

Two bugs these guard against, found running logos-tutorial's LGX spec on
Windows:

- A multi-line `run:` put only its FIRST line behind the `# --- ` header
  comment; the rest ran as live code, outside the capture block. The step ran
  twice, and `lgx create` failed the second time because its package existed.
- Steps ran in `{ }` in the script's own shell, so a step's `set -e` leaked:
  the next failing command killed the whole script, records and all.

doctest runs every step in its own shell, so a generated script must too.

Run with:  python3 tests/test_emit_smoke.py
"""

import importlib.util
import json
import os
import subprocess
import tempfile
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load_engine():
    spec = importlib.util.spec_from_file_location(
        "doctest_engine", os.path.join(ROOT, "doctest.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ENGINE = _load_engine()

SPEC = {
    "name": "emit-smoke isolation",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": "set -eu\necho once >> count.txt\necho second line"},
            {"run": "set -e\nfalse\necho unreachable"},
            {"run": "mkdir -p sub && cd sub && exit 0"},
            {"run": "pwd > where.txt\necho done", "expect_contains": ["done"]},
        ],
    }],
}


def _emit_and_run(spec):
    keys = [key for key, _ in ENGINE.iter_spec_steps(spec)]
    script, _ = ENGINE.emit_smoke_script(spec, "isolation.test.yaml", "so", "linux", keys)
    work = tempfile.mkdtemp()
    with open(os.path.join(work, "smoke.sh"), "w") as handle:
        handle.write(script)
    proc = subprocess.run(["bash", "smoke.sh"], cwd=work, capture_output=True, text=True,
                          env={**os.environ, "EXECS_OUT": "execs.json"})
    return work, script, proc


class EmitSmokeIsolation(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.work, cls.script, cls.proc = _emit_and_run(SPEC)

    def read(self, name):
        with open(os.path.join(self.work, name)) as handle:
            return handle.read()

    def test_headers_are_one_comment_line(self):
        lines = self.script.split("\n")
        for i, line in enumerate(lines):
            if line.startswith("# --- "):
                self.assertTrue(lines[i + 1].startswith("_o=") or lines[i + 1].startswith("mkdir"),
                                f"header followed by live code: {lines[i + 1]!r}")

    def test_multiline_step_runs_once(self):
        self.assertEqual(self.read("count.txt"), "once\n")

    def test_set_e_does_not_end_the_script(self):
        records = json.loads(self.read("execs.json"))
        self.assertEqual(len(records), 4, records.keys())
        statuses = [records[k][0]["status"] for k in sorted(records)]
        self.assertEqual(statuses, ["pass", "fail", "pass", "pass"])
        self.assertNotEqual(self.proc.returncode, 0)

    def test_cd_does_not_carry_over(self):
        self.assertEqual(self.read("where.txt").strip(), os.path.realpath(self.work))


if __name__ == "__main__":
    unittest.main(verbosity=2)
