#!/usr/bin/env python3
"""Run scripts generated by `emit-smoke` and check each step runs once, alone,
exactly as written.

Bugs these guard against, found running real specs on Windows:

- A multi-line `run:` put only its FIRST line behind the `# --- ` header
  comment; the rest ran as live code, outside the capture block. The step ran
  twice, and `lgx create` failed the second time because its package existed.
- Steps ran in `{ }` in the script's own shell, so a step's `set -e` leaked:
  the next failing command killed the whole script, records and all.
- Expects and check_file patterns went raw into a double-quoted `echo`: an odd
  number of `"` made the script unparseable (bash exits 2 mid-run), and `$` was
  expanded.
- Command lines were indented, so a heredoc's `EOF` never matched (another
  parse error) and every multi-line string gained two spaces per line.
- A step with several records (file/run/extra_run/check_file) wrote its key once
  per record. json.load keeps the last, so a failing `run:` before a passing
  `extra_run:` assembled as a pass.
- logos-windows-ci runs the script as `bash -euo pipefail`. Its errexit ended the
  script at the first failing step, before that step's record, so the records
  left behind all passed.
- A selected `ui_test` step produced no line and no record, so the leg passed a
  UI test that never ran.

doctest runs every step in its own shell, so a generated script must too.

Run with:  python3 tests/test_emit_smoke.py
CI also runs it on windows-latest, in the Git for Windows bash the scripts run in.
"""

import contextlib
import importlib.util
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load_engine():
    spec = importlib.util.spec_from_file_location(
        "doctest_engine", os.path.join(ROOT, "doctest.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ENGINE = _load_engine()

SPEC = {
    "name": "emit-smoke isolation",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": "set -eu\necho once >> count.txt\necho second line"},
            {"run": "set -e\nfalse\necho unreachable"},
            {"run": "mkdir -p sub && cd sub && exit 0"},
            {"run": "pwd > where.txt\necho done", "expect_contains": ["done"]},
        ],
    }],
}


# `$` steps first: an odd `"` stops bash at parse time, before anything after it runs.
QUOTING_SPEC = {
    "name": "emit-smoke quoting",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": "echo nothing", "expect_contains": ["$(touch subst) `touch tick` $HOME"]},
            {"run": "echo 'costs $5'", "expect_contains": ["$5"]},
            {"run": """echo '{"result":"probe-call-ok"}'""",
             "expect_contains": ['"result":"probe-call-ok']},
            {"run": "echo nothing", "expect_contains": ['"odd']},
            {"check_file": 'no-such-"file*'},
            {"run": "echo last"},
        ],
    }],
}

# Git for Windows' `ln -s` copies, so it cannot make a dangling link: no such rows there.
SYMLINKS = os.name != "nt"

# check_file fixtures, one per edge case. The odd name holds `"`, `$` and backticks.
CHECK_FILE_SETUP = ("mkdir -p 'my dir' dots empty && touch exists.txt .hidden dots/.x '[ab]' "
                    "'my dir/a b.txt' 'odd \"$q`x`.txt'"
                    + (" && ln -s nowhere dangling" if SYMLINKS else ""))

# What doctest run's glob.glob reports for each pattern; every bash must agree.
CHECK_FILE_CASES = [
    ("exists.txt", "pass"),
    ("missing.txt", "fail"),         # no glob characters: comes back unchanged
    ("my dir/*.txt", "pass"),
    ('odd "$q`x`.txt', "pass"),      # data, never expanded
    ("*hidden", "fail"),             # `*` skips dotfiles
    (".hid*", "pass"),
    ("dots/*", "fail"),
    ("empty/.*", "fail"),            # bash < 5.2 globs `.` and `..`
    ("empty/.", "pass"),             # ...but named literally, `.` counts
    ("[ab]", "fail"),                # a glob matching nothing, though a file has its name
    ("$(touch subst)`touch tick`*", "fail"),
]
if SYMLINKS:  # lstat, as glob.glob
    CHECK_FILE_CASES += [("dangling", "pass"), ("dangl*", "pass")]

CHECK_FILE_SPEC = {
    "name": "emit-smoke check_file",
    "sections": [{
        "title": "Steps",
        "steps": [{"run": CHECK_FILE_SETUP}] + [{"check_file": p} for p, _ in CHECK_FILE_CASES],
    }],
}

# Resolved on PATH: on Windows a bare "bash" can start System32's WSL launcher instead.
BASH = shutil.which("bash") or "bash"
# Each distinct bash here: nixpkgs' has no compgen, macOS /bin/bash is 3.2.
BASHES = sorted({os.path.realpath(b) for b in (BASH, "/bin/bash") if os.path.exists(b)})

HEREDOC_SPEC = {
    "name": "emit-smoke heredoc",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": """cat > config.json <<'EOF'
{"home": "$HOME"}
EOF
cat config.json""", "expect_contains": ['"home": "$HOME"']},
            {"run": "printf '%s\\n' 'first\nsecond' > multiline.txt"},
            {"run": "echo last"},
        ],
    }],
}

# Steps with several records, where a failure is followed by a pass. The file
# write fails because `dir` is a directory; check_file matches nothing.
RECORDS_SPEC = {
    "name": "emit-smoke records",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": "echo main; mkdir dir; exit 3", "extra_run": {"run": "echo verify"}},
            {"file": {"path": "dir", "content": "x"}, "run": "echo ok",
             "check_file": "missing-*"},
            {"run": "echo alone"},
        ],
    }],
}

# Step 0.0 above as scripts from before the fix recorded it: the key twice.
REPEATED_KEY_EXECS = (
    '{"0.0":[{"kind": "run", "cmd": "echo main; mkdir dir; exit 3", "status": "fail", '
    '"exit_code": 3, "output": "main\\n"}],"0.0":[{"kind": "run", "cmd": "echo verify", '
    '"status": "pass", "exit_code": 0, "output": "verify\\n"}]}')

KILLED_SPEC = {
    "name": "emit-smoke killed mid-step",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": "echo kept", "extra_run": {"run": "kill -TERM $$"}},
            {"run": "echo never"},
        ],
    }],
}

# A step sees the options doctest run's `sh -c` has: no errexit, nounset or pipefail.
OPTIONS_SPEC = {
    "name": "emit-smoke step options",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": "case $- in *e*|*u*) exit 1;; esac\nshopt -qo pipefail && exit 2\n"
                    "false | true\necho \"[$UNSET_IN_STEP]\""},
        ],
    }],
}

# Step 0.1 does not parse, so bash stops reading the script there.
PARSE_ERROR_SPEC = {
    "name": "emit-smoke parse error",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": "echo first"},
            {"run": "echo second; fi"},
            {"run": "echo third", "check_file": "*"},
        ],
    }],
}

# Step 0.1 is a UI test the script cannot run. Step 0.3 has `run:`, so doctest run runs
# that and never reaches its ui_test.
UI_TEST_SPEC = {
    "name": "emit-smoke ui_test",
    "sections": [{
        "title": "Steps",
        "steps": [
            {"run": "echo before"},
            {"title": "Drive the app", "ui_test": {
                "launch": "./app/bin/app{exe} --user-dir ./data",
                "tests": [{"action": "wait_for", "texts": ["Ready"]}]}},
            {"run": "echo after"},
            {"run": "echo run wins", "ui_test": {
                "launch": "./app/bin/app{exe}", "tests": [{"action": "sleep", "ms": 1}]}},
        ],
    }],
}

STRICT = ("-euo", "pipefail")  # how logos-windows-ci runs a generated script
NOT_RUN = "not run: the script stopped before this command finished\n"


def _emit_and_run(spec, bash=BASH, flags=()):
    keys = [key for key, _ in ENGINE.iter_spec_steps(spec)]
    script, _ = ENGINE.emit_smoke_script(spec, "isolation.test.yaml", "so", "linux", keys)
    work = tempfile.mkdtemp()
    # LF, as emit-smoke writes it on Linux: bash reads a CR as part of the line.
    with open(os.path.join(work, "smoke.sh"), "w", encoding="utf-8", newline="\n") as handle:
        handle.write(script)
    proc = subprocess.run([bash, *flags, "smoke.sh"], cwd=work, capture_output=True, text=True,
                          env={**os.environ, "EXECS_OUT": "execs.json"})
    return work, script, proc


def _read(work, name):
    with open(os.path.join(work, name)) as handle:
        return handle.read()


def _records(work):
    """{key: (status, exit_code)} from the script's execs.json."""
    execs = json.loads(_read(work, "execs.json"))
    return {key: (recs[0]["status"], recs[0]["exit_code"]) for key, recs in execs.items()}


def _all_records(work):
    """{key: [(kind, status, exit_code)]} for every record; exit_code is None where absent."""
    execs = json.loads(_read(work, "execs.json"))
    return {key: [(r["kind"], r["status"], r.get("exit_code")) for r in recs]
            for key, recs in execs.items()}


def _bash_n(work):
    return subprocess.run([BASH, "-n", "smoke.sh"], cwd=work, capture_output=True, text=True)


def _assemble(work, spec, execs_name):
    """`doctest assemble` on a records file: (process, per-step statuses in the payload)."""
    with open(os.path.join(work, "spec.test.yaml"), "w") as handle:
        yaml.safe_dump(spec, handle)
    proc = subprocess.run([sys.executable, os.path.join(ROOT, "doctest.py"), "assemble",
                           "spec.test.yaml", execs_name, "-o", "results.json"],
                          cwd=work, capture_output=True, text=True)
    if proc.returncode:
        return proc, None
    payload = json.loads(_read(work, "results.json"))
    rows = [row for tutorial in payload["tutorials"] for row in tutorial["rows"]]
    return proc, [[rec["status"] for rec in row["execs"]] for row in rows if row.get("execs")]


class EmitSmokeIsolation(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.work, cls.script, cls.proc = _emit_and_run(SPEC)

    def read(self, name):
        with open(os.path.join(self.work, name)) as handle:
            return handle.read()

    def test_headers_are_one_comment_line(self):
        lines = self.script.split("\n")
        for i, line in enumerate(lines):
            if line.startswith("# --- "):
                self.assertTrue(lines[i + 1].startswith("_o=") or lines[i + 1].startswith("mkdir"),
                                f"header followed by live code: {lines[i + 1]!r}")

    def test_multiline_step_runs_once(self):
        self.assertEqual(self.read("count.txt"), "once\n")

    def test_set_e_does_not_end_the_script(self):
        records = json.loads(self.read("execs.json"))
        self.assertEqual(len(records), 4, records.keys())
        statuses = [records[k][0]["status"] for k in sorted(records)]
        self.assertEqual(statuses, ["pass", "fail", "pass", "pass"])
        self.assertNotEqual(self.proc.returncode, 0)

    def test_cd_does_not_carry_over(self):
        # Under `sub` the file would be missing here. Git Bash spells pwd /c/..., hence basename.
        self.assertEqual(os.path.basename(self.read("where.txt").strip()), os.path.basename(self.work))


class EmitSmokeQuoting(unittest.TestCase):
    """Expects and check_file patterns are data, printed verbatim, never parsed."""

    @classmethod
    def setUpClass(cls):
        cls.work, cls.script, cls.proc = _emit_and_run(QUOTING_SPEC)

    def test_script_parses(self):
        check = _bash_n(self.work)
        self.assertEqual(check.returncode, 0, check.stderr)

    def test_records(self):
        self.assertEqual(_records(self.work), {
            "0.0": ("fail", 90),  # `$` and backticks, missing
            "0.1": ("pass", 0),   # `$`, found
            "0.2": ("pass", 0),   # odd number of `"`, found
            "0.3": ("fail", 90),  # odd number of `"`, missing
            "0.4": ("fail", 1),   # check_file with a `"`, no match
            "0.5": ("pass", 0),
        }, self.proc.stderr)
        self.assertNotEqual(self.proc.returncode, 0)

    def test_failure_messages_are_literal(self):
        self.assertIn('::error::expected output not found: "odd\n', self.proc.stdout)
        self.assertIn("::error::expected output not found: $(touch subst) `touch tick` $HOME\n",
                      self.proc.stdout)
        execs = json.loads(_read(self.work, "execs.json"))
        self.assertEqual(execs["0.4"][0]["output"], 'no match: no-such-"file*\n')

    def test_nothing_in_a_message_runs(self):
        self.assertFalse(os.path.exists(os.path.join(self.work, "subst")))
        self.assertFalse(os.path.exists(os.path.join(self.work, "tick")))


class EmitSmokeCheckFile(unittest.TestCase):
    """check_file passes iff its glob matches an existing path, as in doctest run, under
    every bash here. It used `compgen -G`, which nixpkgs' bash lacks: every check failed."""

    @unittest.skipIf(os.name == "nt", "doctest run does not run on Windows")
    def test_table_is_what_doctest_run_reports(self):
        work = tempfile.mkdtemp()
        subprocess.run([BASH, "-c", CHECK_FILE_SETUP], cwd=work, check=True)
        results = ENGINE.Results(fail_fast=False)
        native = []
        with contextlib.redirect_stdout(io.StringIO()):
            for pattern, _ in CHECK_FILE_CASES:
                passed = results.passed
                ENGINE.handle_check_file({"check_file": pattern}, work, results, False)
                native.append((pattern, "pass" if results.passed > passed else "fail"))
        self.assertEqual(native, CHECK_FILE_CASES)

    def test_every_bash_agrees(self):
        self.assertTrue(BASHES)
        for bash in BASHES:
            with self.subTest(bash=bash):
                work, _, proc = _emit_and_run(CHECK_FILE_SPEC, bash)
                records = _records(work)
                self.assertEqual(records["0.0"], ("pass", 0), proc.stdout)
                self.assertEqual([(pattern, records[f"0.{i}"][0])
                                  for i, (pattern, _) in enumerate(CHECK_FILE_CASES, start=1)],
                                 CHECK_FILE_CASES, proc.stdout)
                execs = json.loads(_read(work, "execs.json"))
                self.assertEqual(execs["0.3"][0]["output"], "my dir/a b.txt\n")
                self.assertEqual(execs["0.2"][0]["output"], "no match: missing.txt\n")
                self.assertFalse(os.path.exists(os.path.join(work, "subst")))
                self.assertFalse(os.path.exists(os.path.join(work, "tick")))


class EmitSmokeVerbatimCommand(unittest.TestCase):
    """A step's lines reach bash exactly as written: heredocs, multi-line strings."""

    @classmethod
    def setUpClass(cls):
        cls.work, cls.script, cls.proc = _emit_and_run(HEREDOC_SPEC)

    def test_script_parses(self):
        check = _bash_n(self.work)
        self.assertEqual(check.returncode, 0, check.stderr)

    def test_records(self):
        self.assertEqual(_records(self.work),
                         {"0.0": ("pass", 0), "0.1": ("pass", 0), "0.2": ("pass", 0)},
                         self.proc.stderr)
        self.assertEqual(self.proc.returncode, 0)

    def test_quoted_heredoc_writes_its_body_unexpanded(self):
        self.assertEqual(_read(self.work, "config.json"), '{"home": "$HOME"}\n')

    def test_multiline_string_keeps_its_lines(self):
        self.assertEqual(_read(self.work, "multiline.txt"), "first\nsecond\n")


class EmitSmokeRecords(unittest.TestCase):
    """Every record of a step reaches the reader, failures included."""

    @classmethod
    def setUpClass(cls):
        cls.work, cls.script, cls.proc = _emit_and_run(RECORDS_SPEC)

    def test_each_step_key_is_written_once(self):
        pairs = json.loads(_read(self.work, "execs.json"), object_pairs_hook=lambda p: p)
        self.assertEqual([key for key, _ in pairs], ["0.0", "0.1", "0.2"])

    def test_plain_json_load_keeps_every_record(self):
        execs = json.loads(_read(self.work, "execs.json"))
        self.assertEqual({key: [(r["kind"], r["status"]) for r in recs]
                          for key, recs in execs.items()}, {
            "0.0": [("run", "fail"), ("run", "pass")],
            "0.1": [("file", "fail"), ("run", "pass"), ("check_file", "fail")],
            "0.2": [("run", "pass")],
        })
        self.assertNotEqual(self.proc.returncode, 0)

    def test_assemble_reports_the_failures(self):
        proc, steps = _assemble(self.work, RECORDS_SPEC, "execs.json")
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("(6 record(s), 3 passed, 3 failed)", proc.stdout)
        self.assertEqual(steps, [["fail", "pass"], ["fail", "pass", "fail"], ["pass"]])

    def test_assemble_keeps_repeated_keys_from_older_scripts(self):
        work = tempfile.mkdtemp()
        with open(os.path.join(work, "old-execs.json"), "w") as handle:
            handle.write(REPEATED_KEY_EXECS)
        proc, steps = _assemble(work, RECORDS_SPEC, "old-execs.json")
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("(2 record(s), 1 passed, 1 failed)", proc.stdout)
        self.assertEqual(steps, [["fail", "pass"]])


class EmitSmokeStrictInvocation(unittest.TestCase):
    """logos-windows-ci runs the script as `bash -euo pipefail`, and that must change no
    record. Its errexit used to end the script at the first failing step, unrecorded."""

    def test_records_match_plain_bash(self):
        specs = {"isolation": SPEC, "quoting": QUOTING_SPEC, "heredoc": HEREDOC_SPEC,
                 "records": RECORDS_SPEC, "check_file": CHECK_FILE_SPEC, "options": OPTIONS_SPEC,
                 "ui_test": UI_TEST_SPEC}
        for bash in BASHES:
            for name, spec in specs.items():
                with self.subTest(bash=bash, spec=name):
                    plain, _, plain_proc = _emit_and_run(spec, bash)
                    strict, _, strict_proc = _emit_and_run(spec, bash, STRICT)
                    self.assertEqual(_all_records(strict), _all_records(plain), strict_proc.stdout)
                    self.assertEqual(strict_proc.returncode, plain_proc.returncode)

    def test_steps_run_without_the_scripts_options(self):
        for bash in BASHES:
            for flags in ((), STRICT):
                with self.subTest(bash=bash, flags=flags):
                    work, _, proc = _emit_and_run(OPTIONS_SPEC, bash, flags)
                    self.assertEqual(_all_records(work), {"0.0": [("run", "pass", 0)]}, proc.stdout)


class EmitSmokeStoppedEarly(unittest.TestCase):
    """A script that stops early (a signal, a parse error) records each command it did not
    finish as failed, so its records cannot read as a pass. A hard kill leaves invalid JSON."""

    def test_killed_mid_step(self):
        for bash in BASHES:
            with self.subTest(bash=bash):
                work, _, proc = _emit_and_run(KILLED_SPEC, bash)
                self.assertNotEqual(proc.returncode, 0)
                pairs = json.loads(_read(work, "execs.json"), object_pairs_hook=lambda p: p)
                self.assertEqual([key for key, _ in pairs], ["0.0", "0.1"])
                execs = json.loads(_read(work, "execs.json"))
                self.assertEqual({key: [(r["status"], r["output"]) for r in recs]
                                  for key, recs in execs.items()},
                                 {"0.0": [("pass", "kept\n"), ("fail", NOT_RUN)],
                                  "0.1": [("fail", NOT_RUN)]})

    def test_parse_error(self):
        for bash in BASHES:
            with self.subTest(bash=bash):
                work, _, proc = _emit_and_run(PARSE_ERROR_SPEC, bash)
                self.assertEqual(proc.returncode, 2, proc.stderr)
                self.assertEqual(_all_records(work), {
                    "0.0": [("run", "pass", 0)],
                    "0.1": [("run", "fail", None)],
                    "0.2": [("run", "fail", None), ("check_file", "fail", None)],
                })

    def test_assemble_counts_them_as_failed(self):
        work, _, _ = _emit_and_run(KILLED_SPEC)
        proc, steps = _assemble(work, KILLED_SPEC, "execs.json")
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("(3 record(s), 1 passed, 2 failed)", proc.stdout)
        self.assertEqual(steps, [["pass", "fail"], ["fail"]])


class EmitSmokeUiTest(unittest.TestCase):
    """A script cannot run a ui_test yet, so it records the step as failed instead of
    leaving it out, and the steps around it still run."""

    def test_recorded_as_failed(self):
        for bash in BASHES:
            for flags in ((), STRICT):
                with self.subTest(bash=bash, flags=flags):
                    work, _, proc = _emit_and_run(UI_TEST_SPEC, bash, flags)
                    self.assertEqual(_all_records(work), {
                        "0.0": [("run", "pass", 0)],
                        "0.1": [("ui_test", "fail", None)],
                        "0.2": [("run", "pass", 0)],
                        "0.3": [("run", "pass", 0)],
                    }, proc.stdout)
                    self.assertEqual(proc.returncode, 1)
                    record = json.loads(_read(work, "execs.json"))["0.1"][0]
                    self.assertEqual(record["cmd"], "./app/bin/app --user-dir ./data")
                    self.assertTrue(record["output"].startswith("not run: "), record["output"])
                    self.assertIn("::error::0.1 Drive the app: not run: ", proc.stdout)

    def test_warns_for_that_step_only(self):
        keys = [key for key, _ in ENGINE.iter_spec_steps(UI_TEST_SPEC)]
        _, warnings = ENGINE.emit_smoke_script(UI_TEST_SPEC, "ui.test.yaml", "dll", "windows",
                                               keys, ".exe")
        self.assertEqual(len(warnings), 1, warnings)
        self.assertIn("step 0.1 ('Drive the app') is a ui_test", warnings[0])

    def test_strict_refuses_to_emit(self):
        work = tempfile.mkdtemp()
        with open(os.path.join(work, "ui.test.yaml"), "w") as handle:
            yaml.safe_dump(UI_TEST_SPEC, handle)
        proc = subprocess.run([sys.executable, os.path.join(ROOT, "doctest.py"), "emit-smoke",
                               "ui.test.yaml", "--platform", "windows", "--strict", "-o", "s.sh"],
                              cwd=work, capture_output=True, text=True)
        self.assertEqual(proc.returncode, 3, proc.stderr)
        self.assertIn("is a ui_test", proc.stderr)

    def test_assemble_counts_it_as_failed(self):
        work, _, _ = _emit_and_run(UI_TEST_SPEC)
        proc, steps = _assemble(work, UI_TEST_SPEC, "execs.json")
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("(4 record(s), 3 passed, 1 failed)", proc.stdout)
        self.assertEqual(steps, [["pass"], ["fail"], ["pass"], ["pass"]])


if __name__ == "__main__":
    unittest.main(verbosity=2)
